### ISSUE TITLE
Update documentation for writing to the default stream in the EU region

### ISSUE THREAD

**Issue by larssn** [googleapis/nodejs-bigquery-storage#261]
I'm trying to write to the `_default` stream (from Cloud Functions), as mentioned in various source files.

But it's not working. I keep getting the error that the table does not exist, while it does. _Also tried generating the table in the US region, but that results in the same error._ But I need it for the EU region.

### Simple proto file (`simple_table_record.proto`)
```proto
// The BigQuery Storage API expects protocol buffer data to be encoded in the
// proto2 wire format. This allows it to disambiguate missing optional fields
// from default values without the need for wrapper types.
syntax = "proto2";

// Define a message type representing the rows in your table. The message
// cannot contain fields which are not present in the table.
message SimpleTableRecord {
  required string name = 1;
}
```

I've generated the associated js file using `grpc_tools_node_protoc --js_out=import_style=commonjs,binary:. simple_table_record.proto`.

### The test script (typescript)
```typescript
import { BigQueryWriteClient, protos } from '@google-cloud/bigquery-storage'
import { getProjectId } from '../../utils'
import { logger } from 'firebase-functions/v1'
import { v4 } from 'uuid'
import * as rec from './proto/simple_table_record_pb'

import FieldDescriptorProto = protos.google.protobuf.FieldDescriptorProto
import Storage = protos.google.cloud.bigquery.storage.v1

export async function writeDefaultStreamTest(
  projectId = getProjectId(),
  datasetId = 'firebase_export',
  tableId = 'simple_table',
) {
  return new Promise(async (resolve, reject) => {
    try {
      const writeClient = new BigQueryWriteClient()

      const parent = `projects/${projectId}/datasets/${datasetId}/tables/${tableId}/streams/_default`
      const [writeStream] = await writeClient.createWriteStream({
        parent,
        writeStream: { type: Storage.WriteStream.Type.COMMITTED },
      })

      logger.log(`Stream created: ${writeStream.name}`)

      const stream = writeClient.appendRows({
        otherArgs: {
          headers: {
            'x-goog-request-params': `write_stream=${writeStream.name}&parent=${parent}`,
          }
        }
      })

      const serializedRows: any[] = []
      const row = new (rec as any).SimpleTableRecord()
      row.row_num = 1
      row.setName(v4())
      serializedRows.push(row.serializeBinary())

      stream.on('data', response => logger.log(response))
      stream.on('error', err => {
        logger.error(err)
        reject(err)
      })
      stream.on('end', () => {
        logger.log('!!!END!!!')
        resolve(null)
      })

      stream.write({
        writeStream: writeStream.name,
        protoRows: {
          writerSchema: {
            protoDescriptor: {
              name: 'SimpleTableRecord',
              field: [{
                name: 'name',
                number: 1,
                type: FieldDescriptorProto.Type.TYPE_STRING,
              }]
            }
          },
          rows: { serializedRows },
        },
      }, undefined, (err) => {
        logger.error(err)
        reject(err)
      })
    } catch (err) {
      logger.error(err)
      reject(err)
    }
  })
}
```

When run, it throws the following error:
```object
Error: 3 INVALID_ARGUMENT: Invalid table name. Entity: projects/<project-name>/datasets/firebase_export/tables/simple_table/streams/_default
    at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/src/client.ts:343:36)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/src/client-interceptors.ts:462:34)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
    at /workspace/node_modules/@grpc/grpc-js/src/call-stream.ts:330:24
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  code: 3,
  details: 'Invalid table name. Entity: projects/<project-name>/datasets/firebase_export/tables/simple_table/streams/_default',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  note: 'Exception occurred in retry method that was not classified as transient'
} 
```

The BigQuery table schema:
```
{
  name: string (nullable)
}
```

**Comment by larssn** [comment]
So I got it working by not calling "createWriteStream", and making the following changes:

```typescript
const parent = `projects/${projectId}/datasets/${datasetId}/tables/${tableId}`
const writeStreamName = `projects/${projectId}/datasets/${datasetId}/tables/${tableId}/streams/_default`
// const [writeStream] = await writeClient.createWriteStream({
//   parent,
//   writeStream: { type: Storage.WriteStream.Type.COMMITTED },
// })

const stream = writeClient.appendRows({
    otherArgs: {
        headers: {
        'x-goog-request-params': `write_stream=${writeStreamName}&parent=${parent}`,
        }
    }
})
```

You can turn this issue into a feature request for better docs. They are incomplete and pretty vague.

**Comment by steffnay** [comment]
@larssn This is demonstrated in the code samples:

- https://github.com/googleapis/nodejs-bigquery-storage/blob/fb8acf1f4eab7823132159bcf5927c9eda6374e2/samples/append_rows_pending.js#L84
- https://github.com/googleapis/nodejs-bigquery-storage/blob/fb8acf1f4eab7823132159bcf5927c9eda6374e2/samples/append_rows_proto2.js#L147

Is there another location in the docs you were referencing where this is not present?

**Comment by larssn** [comment]
@steffnay Thanks for stopping by!

But writing to the default stream is never demonstrated, and the existing samples seems to have come from the python samples, which is better than nothing. I just wish there were some dedicated samples; more explanatory, maybe in typescript, to get the point across. 🙂

Another thing I've run into that I haven't been able to solve yet, is writing a `protoDescriptor` for nested fields (record/struct).

Here's what I go so far, but it's not accepted by grcp:

```typescript
   stream.write({
      writeStream: writeStreamPath,
      protoRows: {
        writerSchema: {
          protoDescriptor: {
            name: 'SimpleTableRecord',
            field: [
              {
                name: 'record',
                number: 1,
                label: FieldDescriptorProto.Label.LABEL_OPTIONAL,
                type: FieldDescriptorProto.Type.TYPE_MESSAGE,
                type_name: 'SimpleTableRecord.SampleStruct', // Also tried just 'SampleStruct'.
                field: [
                  {
                    number: 1,
                    name: 'name',
                    label: FieldDescriptorProto.Label.LABEL_OPTIONAL,
                    type: FieldDescriptorProto.Type.TYPE_STRING,
                  },
                  {
                    number: 2,
                    name: 'value',
                    label: FieldDescriptorProto.Label.LABEL_OPTIONAL,
                    type: FieldDescriptorProto.Type.TYPE_STRING,
                  }
                ],
              },
            ]
          }
        },
        rows: { serializedRows },
      },
    })
```

With this being the proto file:

```
message SimpleTableRecord {
  message SampleStruct {
    optional string name = 1;
    optional string value = 2;
  }

  optional SampleStruct record = 1;
}
```

Thanks for reading

**Comment by ben790924** [comment]
@larssn Hello, have you solved the issue about nested message type  in .proto file and the way of declaring proto descriptors ?

**Comment by larssn** [comment]
@ben790924 Sadly no. I've looked all over for where `protoDescriptor` is parsed, without any luck.

Let me know if you find it

**Comment by ben790924** [comment]
Thanks for your information。

BTW, I found this project written in Go. What's the difference is it declares message outside of main message in a .proto file. So you can jsut declare descriptor as JS objects does。(I have not tested it in JS yet, but hope this helps) 


[Go Proto Example](https://github.com/alexflint/bigquery-storage-api-example)
